from moodle_sync_faces import MoodleSyncFaces

credentials_file = "../data/credentials.json"
ms = MoodleSyncFaces.from_json(credentials_file)
response = ms.call("core_webservice_get_site_info")
print(response)
print(response["userid"])

# SystemError: ('Error calling Moodle API\n', {'exception': 'webservice_access_exception', 'errorcode': 'accessexception', 'message': 'Access control exception (Access to the function core_webservice_get_site_info() is not allowed.\n                     There could be multiple reasons for this:\n                     1. The service linked to the user token does not contain the function.\n                     2. The service is user-restricted and the user is not listed.\n                     3. The service is IP-restricted and the user IP is not listed.\n                     4. The service is time-restricted and the time has expired.\n                     5. The token is time-restricted and the time has expired.\n                     6. The service requires a specific capability which the user does not have.\n                     7. The function is called with username/password (no user token is sent)\n                     and none of the services has the function to allow the user.\n                     These settings can be found in Administration > Site administration\n                     > Server > Web services > External services and Manage tokens.)', 'debuginfo': 'Access to the function core_webservice_get_site_info() is not allowed.\n                     There could be multiple reasons for this:\n                     1. The service linked to the user token does not contain the function.\n                     2. The service is user-restricted and the user is not listed.\n                     3. The service is IP-restricted and the user IP is not listed.\n                     4. The service is time-restricted and the time has expired.\n                     5. The token is time-restricted and the time has expired.\n                     6. The service requires a specific capability which the user does not have.\n                     7. The function is called with username/password (no user token is sent)\n                     and none of the services has the function to allow the user.\n                     These settings can be found in Administration > Site administration\n                     > Server > Web services > External services and Manage tokens.'})

